services:
  - type: static
    name: front-idiomas
    buildCommand: npm install && npm run build
    publishPath: dist/webapp/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
